config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      resources :cocktails, only: [:index, :create, :new, :show, :destroy ]  do
        resources :doses, only: [:create, :new]
  end
  resources :doses, only: [:destroy]

  resources :ingredients, only: [:index, :create, :new, :destroy]

  root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses, :dependent => :delete_all
  has_many :ingredients, through: :doses

  mount_uploader :photo, PhotoUploader

end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: {scope: :ingredient}

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
   validates :name, uniqueness: true
   validates :name, presence: true
   has_many :doses
   before_destroy :check_for_cocktail


  private

  def check_for_cocktail
    if self.doses.count > 0
      raise CustomException.new("Cannot delete while used by cocktail.")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :destroy]

  def index
    filter= "'%#{params[:search]}%'"
    @filter_form = params[:search]
    @cocktails = Cocktail.where("name ILIKE #{filter}")
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(review_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end


  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def review_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [:new, :show, :create, :destory]

  def new
    @dose = Dose.new
    @dose.cocktail = @cocktail
  end

  def create
    @dose = Dose.new(review_params)
    @dose.cocktail = @cocktail
    # byebug
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
      #render :template => "cocktails/show"
    end
  end

  def destroy
    # byebug
    dose = Dose.find(params[:id])
    dose.destroy
    redirect_to request.referrer
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def review_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
before_action :find_ingredient, only: [:destroy]


  def index
    @ingredients = Ingredient.all
  end

  def destroy
    @ingredient.destroy
    redirect_to request.referrer
  end

  def new
     @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(review_params)
    # byebug
    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
      #render :template => "cocktails/show"
    end
  end

 private

  def find_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def review_params
    params.require(:ingredient).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_card.html.erb
<div class="card-index">
  <% if cocktail.photo? %>
  <%= cl_image_tag cocktail.photo.url(:thumnail) %>
  <% else %>
   <%= cl_image_tag("ccdetbkyfmcduo2q0vg8.jpg", :height=>128, :width=>256, :crop=>"fit") %>
  <%end%>
  <div class="container-card">
    <h4><b><%=cocktail.name%></b></h4>
    <p><%=link_to "Details", cocktail_path(cocktail)%></p>
  </div>
</div>

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-inputs">
  <%= f.input :photo %>
  </div>
  <%= f.input :photo_cache, as: :hidden %>
  <div class="form-actions">
    <%= f.button :submit,:class => "btn btn-primary" %>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<span id="banner-typed-text"></span>
<div class="row">
<% @cocktails.each do |cocktail|%>
<div class="col-12 col-md-4">
  <div class="card">
    <%= render partial:'card', locals: {cocktail: cocktail}  %>
  </div>
</div>
<% end %>
</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<div class="form-new">
<%= render 'form', cocktail: @cocktail %>
</div>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h3> Cocktail Name: </h3>
    <p><%= @cocktail.name %> </p>
    <div class="image-show">
    <% if @cocktail.photo? %>
      <%= cl_image_tag @cocktail.photo.url(:original)%>
      <% else %>
       <%= cl_image_tag("ccdetbkyfmcduo2q0vg8.jpg", :height=>256, :width=>512, :crop=>"fit") %>
    <%end%>
    </div>
  </div>
  <div class="col-md-6">
    <h3>Incredients:</h3>
    <ul class="list-unstyled">
      <%@cocktail.doses.each do |dose|%>
        <li><%=dose.description%> <%=dose.ingredient.name%>
          <%=link_to dose_path(dose), :method => :delete do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </li>
      <%end%>
    </ul>

    <ul class="list-unstyled">
    <li><%=link_to "Add new ingredient", new_cocktail_dose_path(@cocktail),:class => "btn btn-primary"%></li>
    <li><%=link_to "Delete Cocktail", cocktail_path(@cocktail), :method => :delete ,:class => "btn btn-warning", :id => "delete-cocktail"%></li>
    </ul>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description%>
  </div>
  <div class="form-inputs">
  <%= f.association :ingredient, as: :select %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doses/new.html.erb
<h1>Add Ingredient</h1>

<div class="form-new">
<%= render 'form', dose: @dose, cocktail: @cocktail %>
</div>

<%= link_to 'Back', cocktails_path %>

app/views/ingredients/_form.html.erb
<%= simple_form_for [@ingredient] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name%>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ingredients/index.html.erb
<h3> Available ingredients</h3>
<%=link_to "Add new ingredient", new_ingredient_path,:class => "btn btn-primary"%>

<ul class="list-unstyled">
  <%@ingredients.each do |ingredient| %>

  <li>
    <%=ingredient.name%>
    <%=link_to ingredient_path(ingredient), :method => :delete do %>
      <i class="far fa-trash-alt"></i>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container text-center">
    <%= yield %>
    </div>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_navbar.html.erb
 <div class="navbar-wagon">
    <!-- Logo -->
     <%=link_to cocktails_path, :class => "navbar-wagon-brand navbar-wagon-link" do%>
     Cocktails
     <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

    <form class="form-inline" action="/cocktails" method="get">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="search" class="form-control" name="search" value=<%= @filter_form %>>
    <button type="submit" class="btn btn-primary">Search</button>
    </form>

    <%=link_to "New Cocktail", new_cocktail_path, :class => "btn btn-warning", :id => "new-cocktail" %>
    <%=link_to "Ingredients", ingredients_path, :class => "btn btn-warning", :id => "new-cocktail" %>
    </div>

    <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%=link_to "New Cocktail", new_cocktail_path %></li>
        <li><%=link_to "Ingredients", ingredients_path %></li>
        <li>
            <form action="/cocktails" method="get">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <input type="search" class="form-control" name="search" placeholder="search..."value=<%= @filter_form %>>
            <button type="submit" hidden />
            </form>
        </li>
      </ul>
    </div>
  </div>
  </div>